
volumes:
  db-data:

services:
  server:
    build:
      context: .
    ports:
      - 8000:80
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=boletos_api
      - DB_USERNAME=postgres
      - DB_PASSWORD=wrgs2703    
      - APP_NAME=boletos-api
      - APP_ENV=local
      - APP_KEY=base64:lGAHdmePRKP2DX4BEWNf7UKP1ZBPuHXpDP1bpEe3xX4=
      - APP_DEBUG=true
      - APP_TIMEZONE=UTC      
    container_name: server
  db:
    image: postgres
    restart: always
    container_name: db
    environment:
      - POSTGRES_PASSWORD=wrgs2703
      - POSTGRES_DB=boletos_api
    volumes:
      - db-data:/var/lib/postgresql/data